// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.service.etservice.grpc;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hallo.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string loginName = 1;</code>
   * @return The loginName.
   */
  String getLoginName();
  /**
   * <code>string loginName = 1;</code>
   * @return The bytes for loginName.
   */
  com.google.protobuf.ByteString
      getLoginNameBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>int64 id = 4;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string email = 5;</code>
   * @return The email.
   */
  String getEmail();
  /**
   * <code>string email = 5;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string phone = 6;</code>
   * @return The phone.
   */
  String getPhone();
  /**
   * <code>string phone = 6;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();
}
