// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.grpc.service;

public interface loginNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hallo.loginName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string loginName = 1;</code>
   * @return The loginName.
   */
  java.lang.String getLoginName();
  /**
   * <code>string loginName = 1;</code>
   * @return The bytes for loginName.
   */
  com.google.protobuf.ByteString
      getLoginNameBytes();
}
