// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.grpc.service;

public final class UserPhoto {
  private UserPhoto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hallo_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hallo_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hallo_loginName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hallo_loginName_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\005hallo\"c\n\004User\022\021\n\tloginName" +
      "\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\n" +
      "\n\002id\030\004 \001(\003\022\r\n\005email\030\005 \001(\t\022\r\n\005phone\030\006 \001(\t" +
      "\"\036\n\tloginName\022\021\n\tloginName\030\001 \001(\t2D\n\013User" +
      "Service\0225\n\022getUserByLoginName\022\020.hallo.lo" +
      "ginName\032\013.hallo.User\"\000B\'\n\020com.grpc.servi" +
      "ceB\tUserPhotoP\001\210\001\001\242\002\002HIb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_hallo_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hallo_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hallo_User_descriptor,
        new java.lang.String[] { "LoginName", "Name", "Password", "Id", "Email", "Phone", });
    internal_static_hallo_loginName_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hallo_loginName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hallo_loginName_descriptor,
        new java.lang.String[] { "LoginName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
